### ISSUE TITLE
Not compatible with FloodGate2.0 

### ISSUE THREAD

**Issue by MC-Nirvana** [games647/FastLogin#535]
[//]: # (Lines in this format are considered as comments and will not be displayed.)
[//]: # (Before reporting make sure you're running the **latest build** of the plugin and checked for existing issues!)

### What behaviour is observed:
[//]: # (What happened?)
Fastlogin is not compatible with floodgate 2.0, so players cannot enter the server and report an error
### What behaviour is expected:
[//]: # (What did you expect?)
Players enter normally, and there is no error in the console
### Steps/models to reproduce:
[//]: # (The actions that cause the issue. Please explain it in detail)
1：Install FastLogin
2：Install FloodGate2.0
3：Join server
### Screenshots (if applicable)
[//]: # (You can drop the files here directly)
None
### Plugin list:
[//]: # (This can be found by running `/pl`)
**BungeeCord：**
AuthMeBungee-2.2.0-SNAPSHOT.jar
BungeeSafeguard.main.jar
FastLoginBungee.jar
floodgate-bungee.jar
Geyser-BungeeCord.jar
**Spigot**
AuthMe-5.6.0-SNAPSHOT.jar
BedrockPlayerManager-1.4.jar
FastLoginBukkit.jar
floodgate-spigot.jar
### Environment description
[//]: # (Server software with exact version number, Minecraft version, SQLite/MySQL/MariaDB, ...)
Server core version：Travertine Build 184，Tuinity Build 229
MySQL version：MySQL 5.7.33
### Plugin version or build number (don't write latest):
[//]: # (This can be found by running `/version plugin-name`.)
1.11-SNAPSHOT-7192dcd
### Server Log:
[//]: # (No images please - only the textual representation)
[Hastebin](https://hastebin.com/) / [Gist](https://gist.github.com/) link of the error, stacktrace or the complete log (if any)
https://hastebin.com/exukasaqoy.properties
### Configuration:
[//]: # (No images please - only the textual representation)
[//]: # (remember to delete any sensitive data)
[Hastebin](https://hastebin.com/) / [Gist](https://gist.github.com/) link of your config.yml file 
https://hastebin.com/asiyugehan.yaml

**Comment by games647** [comment]
Argh, okay the source of this issue is that Java tries to load the class although we don't use it. Similar with ProtocolLib. I'll fix it when I find some time.

**Comment by Smart123s** [comment]
Actually, the first working version of FastLogin Bungee with Floodgate 2.0 support is 1.11-SNAPSHOT- https://github.com/games647/FastLogin/commit/1385f0c7301dbe4a299fdf09ec3294f17991be0d (which is newer than 1.11-SNAPSHOT- https://github.com/games647/FastLogin/commit/7192dcdf07b72e930472de7fab2ac02134265515) so simply updating the plugin will solve the problem.
However, the [CI server](https://ci.codemc.io/job/Games647/job/FastLogin/changes) builds the plugin from https://github.com/AuthMe/FastLogin instead of this repo, and since AuthMe's fork is outdated, you won't be able to download a working version from there.

Here is a build I've compiled based on https://github.com/games647/FastLogin/commit/d1109a:
- [FastLogin-d1109ac.zip](https://github.com/games647/FastLogin/files/6643988/FastLogin-d1109ac.zip)
SHA-256: dc3e3f152c1309386f59ec2e044dff12df16dda7436b8c563893bdf90a209e73
_*Both Bukkit and Bungee included; [GitHub doesn't allow JAR files](https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/attaching-files), so I had to zip them._

**Comment by games647** [comment]
I pushed it to the other repo. Thanks for pointing out.

**Comment by ipozow** [comment]
For me it is still not working, does Geyser need an update in order to work? I am getting this error: https://gist.github.com/ipozow/0be4aca73a76eeddb74417819692b79e

**Comment by games647** [comment]
@ipozow baede33abc12f381577e075cbcdf3f3874995924
